services:

  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - .:/var/www:cached
    networks:
      - laravel-network

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    image: nginx
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - .:/var/www
      - ./gateway:/var/www/gateway
      - ./master:/var/www/master
      - ./frontend:/var/www/frontend
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel-network

  ####################################################################################################
  # Service 1: Laravel App 1
  ####################################################################################################
  gateway:
    build:
      context: ./gateway
    volumes:
      - ./gateway:/var/www/html
    networks:
      laravel-network:
        aliases:
          - gateway-alias # Set an alias for the gateway service
    depends_on:
      - db
      - php
      - master

  ####################################################################################################
  # Service 2: Laravel App 2
  ####################################################################################################
  master:
    build:
      context: ./master
    volumes:
      - ./master:/var/www/html
    networks:
      laravel-network:
        aliases:
          - master-alias # Set an alias for the master service
    depends_on:
      - db
      - php

  ####################################################################################################
  # Service 2: frondend vue
  ####################################################################################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - ./frontend:/var/www/html
      - /frontend/node_modules
    networks:
      - laravel-network

  ####################################################################################################
  # DATABASE (MySQL)
  ####################################################################################################
  db:
    image: mysql:8.1
    ports:
      - 3366:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway_db
      MYSQL_USER: gateway
      MYSQL_PASSWORD: password
    networks:
      - laravel-network

  ####################################################################################################
  # phpMyAdmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8085:80
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - .docker/phpmyadmin/sessions:/sessions
    networks:
      - laravel-network

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
    image: axllent/mailpit:latest
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - laravel-network

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - 6379:6379
    networks:
      - laravel-network


networks:
  laravel-network:
    driver: bridge

  # ####################################################################################################
  # # DATABASE (MariaDB)
  # ####################################################################################################
  # db:
  #     image: mariadb:10.11
  #     ports:
  #         - 3306:3306
  #     volumes:
  #         - .docker/db/data:/var/lib/mysql
  #         - .docker/logs:/var/log/mysql
  #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: laravel_db_name
  #         MYSQL_USER: laravel_db_user
  #         MYSQL_PASSWORD: laravel_db_pass

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  # db:
  #     image: postgres:16
  #     ports:
  #         - 5432:5432
  #     volumes:
  #         - .docker/db/data:/var/lib/postgresql/data
  #         - .docker/db/sql:/docker-entrypoint-initdb.d
  #     environment:
  #         - POSTGRES_USER=refactorian
  #         - POSTGRES_PASSWORD=refactorian
  #         - POSTGRES_DB=refactorian

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  # pgadmin:
  #     image: dpage/pgadmin4
  #     ports:
  #         - 5050:80
  #     environment:
  #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #         - PGADMIN_DEFAULT_PASSWORD=password
  #     depends_on:
  #         - db
